---
title: "Assignment 1"
author: "Maria Bologna"
date: '2023-05-20'
output: html_document
---

# ASSIGNMENT 1 - Plot deconstruction ####

## Importing dataset

```{r}
#`Coral.Data,.1995.2019.xlsx...R.Worthy` <- read.csv("C:/Users/eanbr/Desktop/JCU Masters/Semester 3/MB5370 Techniques in Marine Science 1/github/mb5370/Data Science Module/data/Coral Data, 1995-2019.xlsx - R-Worthy.csv")

# trueyear = as.character.Date(`Coral.Data,.1995.2019.xlsx...R.Worthy`$year)

# corals <- cbind(`Coral.Data,.1995.2019.xlsx...R.Worthy`,trueyear)
```

## Installing required R packages

```{r}
#install.packages("ggridges")
library(ggridges)

#install.packages("ggtext")
library(ggtext)
```

## Deconstructing plot

```{r}
#deconstructedplot <- ggplot(corals, aes(x = area, y = trueyear))+
#  geom_density_ridges(aes(fill=trueyear))+
#  scale_x_continuous(limits = c(0,2000))+
#  labs(x = "2D Surface Area (cm^2)",
#       y = "Survey year",
#       title="Size distribution of *Pocillopora* spp. colonies in Devil's Crown, Galapagos Islands",
#       subtitle = "Surface area by count and survey year")+
#  theme_minimal()+
#  theme(legend.position = 'none', plot.title = ggtext::element_markdown())+
#  geom_point(position=position_jitter(), shape=23,stroke=0, color='black', size=2.5, alpha=0.7, aes(fill=trueyear))#+scale_color_brewer(palette="Set2")

## Saving new plot

# deconstructedplot
```

